import { ResponseBase } from 'src/app/models/response-base.model';

export class JobModel {
    lockFlag: string;
    id: string;
    name: string;
    lastmodifieddate: string;
    deleted: number;
    hrcontactid: string;
    hmcontactid: string;
    grade: string;
    ctccurrency: string;
    ctcfrom: number;
    ctcto: number;
    ctcrangeactual: string;
    ctcfrominr: number;
    ctctoinr: number;
    ctcrangeinr: string;
    experiencefrom: number;
    experienceto: number;
    experiencerange: string;
    industrygroupid: number;
    industrygrouptext: string;
    locationcities: string;
    workinghours: string;
    workingshift: string;
    workingdays: string;
    numberofopening: number;
    jobtype: string;
    recruitmentdrivedate: string;
    gradeposition: string;
    industrydesignationlevel: string;
    staffingtitle: string;
    agefrom: number;
    ageto: number;
    agerange: string;
    positiontype: string;
    status: string;
    interviewvenueid: string;
    venueaddresstext: string;
    jobstartdate: string;
    jobclosedate: string;
    priority: string;
    sourcingstatus: string;
    sourcingdifficulty: string;
    bussinessdivisionid: string;
    bussinessdivisiontext: string;
    functionalgroupid: number;
    functionalgrouptext: string;
    closedreason: string;
    bdanchorid: string;
    bdanchorname: string;
    typeofassignment: string;
    joborder: string;
    projectduration: string;
    ghjobcode: string;
    descriptionnote: string;
    clientsheetid: number;
    clientsheetname: string;
    mailbodytemplateid: number;
    mailbodyname: string;
    recruitmentmailids: string;
    createdby: string;
    modifiedby: string;
    createdusername: string;
    modifiedusername: string;
    createddate: string;
    hrcontactname: string;
    hmcontactname: string;
    mspaccountid: string;
    mspaccountname: string;
    accountname: string;
    ismsp: number;
    primaryaccount: string;
    clientrateon: string;
    rateunit: string;
    clientrate: string;
    deliveryanchorid: string;
    deliveryanchorname: string;
    clientportalid: string;
    positionstatus: string;
    positionnote: string;
    accountid: string;
    revenue: string;
    entity: string;
    clientjobcode: string;
    ishotnote: number;
    ispublish: number;
    whatsappnumber: string;
    portal: string;
    constructor() {
        this.lockFlag = '';
        this.id = '';
        this.name = '';
        this.lastmodifieddate = '';
        this.deleted = 0;
        this.hrcontactid = '';
        this.hmcontactid = '';
        this.grade = '';
        this.ctccurrency = '';
        this.ctcfrom = 0;
        this.ctcto = 0;
        this.ctcrangeactual = '';
        this.ctcfrominr = 0;
        this.ctctoinr = 0;
        this.ctcrangeinr = '';
        this.experiencefrom = 0;
        this.experienceto = 0;
        this.experiencerange = '';
        this.industrygroupid = 0;
        this.industrygrouptext = '';
        this.locationcities = '';
        this.workinghours = '';
        this.workingshift = '';
        this.workingdays = '';
        this.numberofopening = 0;
        this.jobtype = '';
        this.recruitmentdrivedate = '';
        this.gradeposition = '';
        this.industrydesignationlevel = '';
        this.staffingtitle = '';
        this.agefrom = 0;
        this.ageto = 0;
        this.agerange = '';
        this.positiontype = '';
        this.status = '';
        this.interviewvenueid = '';
        this.venueaddresstext = '';
        this.jobstartdate = '';
        this.jobclosedate = '';
        this.priority = '';
        this.sourcingstatus = '';
        this.sourcingdifficulty = '';
        this.bussinessdivisionid = '';
        this.bussinessdivisiontext = '';
        this.functionalgroupid = 0;
        this.functionalgrouptext = '';
        this.closedreason = '';
        this.bdanchorid = '';
        this.bdanchorname = '';
        this.typeofassignment = '';
        this.joborder = '';
        this.projectduration = '';
        this.ghjobcode = '';
        this.descriptionnote = '';
        this.clientsheetid = 0;
        this.clientsheetname = '';
        this.mailbodytemplateid = 0;
        this.mailbodyname = '';
        this.recruitmentmailids = '';
        this.createdby = '';
        this.modifiedby = '';
        this.createdusername = '';
        this.modifiedusername = '';
        this.createddate = '';
        this.hrcontactname = '';
        this.hmcontactname = '';
        this.mspaccountid = '';
        this.mspaccountname = '';
        this.accountname = '';
        this.ismsp = 0;
        this.primaryaccount = '';
        this.clientrateon = '';
        this.rateunit = '';
        this.clientrate = '';
        this.deliveryanchorid = '';
        this.deliveryanchorname = '';
        this.clientportalid = '';
        this.positionstatus = '';
        this.positionnote = '';
        this.accountid = '';
        this.revenue = '';
        this.entity = '';
        this.clientjobcode = '';
        this.ishotnote = 0;
        this.ispublish = 0;
        this.whatsappnumber = '';
        this.portal = '';
    }
}
export class JobModelWithResponse extends ResponseBase {
    data: Array<JobModel>;
    constructor() {
        super();
        this.data = Array<JobModel>();
    }
}