import { ResponseBase } from 'src/app/models/response-base.model';
import { HelperModel } from './helper.model';
import { IndustryModel, IndustryGroupModel } from 'src/app/models/master-data/industry.model';

export class ContactModel {
    account: HelperModel;
    anchor: HelperModel;
    industry: Array<IndustryModel>;
    industrygroup: Array<IndustryGroupModel>;
    boardnumber: string;
    boardnumbercitycode: number;
    boardnumberfull: string;
    websiteurl: string;
    accountid: string;
    accountname: string;
    addressid: string;
    anchorid: string;
    anchorname: string;
    cityname: string;
    contactsecuritygroup: string;
    createdby: string;
    createddate: string;
    createdusername: string;
    deleted: number;
    department: string;
    description: string;
    designation: string;
    emailvalidation: number;
    firstname: string;
    gender: string;
    id: string;
    industriesid: string;
    industriestext: string;
    industrygroupid: string;
    industrygrouptext: string;
    ishotnote: number;
    ispublish: number;
    istargeted: string;
    jobgrade: string;
    lastmodifieddate: string;
    lastname: string;
    leadanchor: HelperModel;
    leadanchorid: string;
    leadcategory: string;
    leadsource: string;
    level: string;
    midlename: string;
    mobilecountrycode: number;
    mobilenumber: string;
    modifiedby: string;
    modifiedusername: string;
    ofcphncitycode: number;
    ofcphncountrycode: number;
    officephone: string;
    officephonefull: string;
    personalmailid: string;
    personalmobilecountrycode: number;
    personalmobilenumber: string;
    previouscontactid: string;
    qwalificationweightage: number;
    referedby: string;
    reporttoid: string;
    reporttoname: string;
    resumeid: number;
    revenuecurrency: string;
    revenuepotential: number;
    revenuepotentialinr: number;
    revenuetenurecycle: string;
    revenuetenurefrom: string;
    revenuetenureto: string;
    salutation: string;
    skypid: string;
    status: string;
    subtitle: string;
    title: string;
    totalrevenuepotential: string;
    whatsappnumber: string;
    workingmailid: string;
    name: string;
    reportto: HelperModel;
    constructor() {
        this.account = new HelperModel();
        this.anchor = new HelperModel();
        this.industry = Array<IndustryModel>();
        this.industrygroup = Array<IndustryGroupModel>();
        this.websiteurl = '';
        this.accountid = '';
        this.accountname = '';
        this.addressid = '';
        this.anchorid = '';
        this.anchorname = '';
        this.cityname = '';
        this.contactsecuritygroup = '';
        this.createdby = '';
        this.createddate = '';
        this.createdusername = '';
        this.deleted = 0;
        this.department = '';
        this.description = '';
        this.designation = '';
        this.emailvalidation = 0;
        this.firstname = '';
        this.gender = '';
        this.id = '';
        this.industriesid = '';
        this.industriestext = '';
        this.industrygroupid = '';
        this.industrygrouptext = '';
        this.ishotnote = 0;
        this.ispublish = 0;
        this.istargeted = '';
        this.jobgrade = '';
        this.lastmodifieddate = '';
        this.lastname = '';
        this.leadanchor = new HelperModel();
        this.leadanchorid = '';
        this.leadcategory = '';
        this.leadsource = '';
        this.level = '';
        this.midlename = '';
        this.mobilecountrycode = 0;
        this.mobilenumber = '';
        this.modifiedby = '';
        this.modifiedusername = '';
        this.ofcphncitycode = 0;
        this.ofcphncountrycode = 0;
        this.officephone = '';
        this.officephonefull = '';
        this.personalmailid = '';
        this.personalmobilecountrycode = 0;
        this.personalmobilenumber = '';
        this.previouscontactid = '';
        this.qwalificationweightage = 0;
        this.referedby = '';
        this.reporttoid = '';
        this.reporttoname = '';
        this.resumeid = 0;
        this.revenuecurrency = '';
        this.revenuepotential = 0;
        this.revenuepotentialinr = 0;
        this.revenuetenurecycle = '';
        this.revenuetenurefrom = '';
        this.revenuetenureto = '';
        this.salutation = '';
        this.skypid = '';
        this.status = '';
        this.subtitle = '';
        this.title = '';
        this.totalrevenuepotential = '';
        this.whatsappnumber = '';
        this.workingmailid = '';
        this.name = '';
        this.reportto = new HelperModel();
    }
}
export class ContactModelWithResponse extends ResponseBase {
    data: Array<ContactModel>;
    contact: ContactModel;
    constructor() {
        super();
        this.data = Array<ContactModel>();
        this.contact = new ContactModel();
    }
}