// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    'aws_project_region': 'ap-south-1',
    'aws_cognito_identity_pool_id': 'ap-south-1:ef59d210-6023-43c5-bf10-dacf197039b6',
    'aws_cognito_region': 'ap-south-1',
    'aws_user_pools_id': 'ap-south-1_stZnl3OGB',
    'aws_user_pools_web_client_id': '690os8q5ijkn4h16dk2fq6oob'

};

export default awsmobile;
