import { ResponseBase } from 'src/app/models/response-base.model';

export class AccountModel {
    pancardno: string;
    internalrecruitmentteam: string;
    boardnumbercountrycode: number;
    lock_flag: string;
    anchorid: string;
    parentaccountname: string;
    modifiedusername: string;
    revenue: string;
    ishotnote: number;
    ispublish: number;
    taleourl: string;
    createdby: string;
    accountcategory: string;
    id: string;
    specialities: string;
    createdusername: string;
    globalhuntclient: string;
    proposedservice: string;
    boardnumbercitycode: number;
    domainname: string;
    revenuefromdate: string;
    shortname: string;
    totalrevenue: string;
    locationbocitywise: string;
    name: string;
    modifiedby: string;
    totaljobs: number;
    status: string;
    createddate: number;
    accounttype: string;
    description: string;
    parentid: string;
    boardnumber: string;
    isaccount: number;
    empanelmentfromdate: string;
    logoname: string;
    boardnumberfull: string;
    empanelmentcycle: string;
    qualificationweightage: number;
    revenuecycle: string;
    lastmodifieddate: number;
    organizationtype: string;
    totalcontactrevenue: string;
    revenuetodate: string;
    deleted: number;
    websiteurl: string;
    anchorname: string;
    revenuecurrency: string;
    empanelmenttodate: string;
    memberof: string;
    employee: string;
    siccode: string;
    rating: string;
    ownership: string;
    vendorcode: string;
    constructor() {
        this.pancardno = '';
        this.internalrecruitmentteam = '';
        this.boardnumbercountrycode = 0;
        this.lock_flag = '';
        this.anchorid = '';
        this.parentaccountname = '';
        this.modifiedusername = '';
        this.revenue = '';
        this.ishotnote = 0;
        this.ispublish = 0;
        this.taleourl = '';
        this.createdby = '';
        this.accountcategory = '';
        this.id = '';
        this.specialities = '';
        this.createdusername = '';
        this.globalhuntclient = '';
        this.proposedservice = '';
        this.boardnumbercitycode = 0;
        this.domainname = '';
        this.revenuefromdate = '';
        this.shortname = '';
        this.totalrevenue = '';
        this.locationbocitywise = '';
        this.name = '';
        this.modifiedby = '';
        this.totaljobs = 0;
        this.status = '';
        this.createddate = 0;
        this.accounttype = '';
        this.description = '';
        this.parentid = '';
        this.boardnumber = '';
        this.isaccount = 0;
        this.empanelmentfromdate = '';
        this.logoname = '';
        this.boardnumberfull = '';
        this.empanelmentcycle = '';
        this.qualificationweightage = 0;
        this.revenuecycle = '';
        this.lastmodifieddate = 0;
        this.organizationtype = '';
        this.totalcontactrevenue = '';
        this.revenuetodate = '';
        this.deleted = 0;
        this.websiteurl = '';
        this.anchorname = '';
        this.revenuecurrency = '';
        this.empanelmenttodate = '';
        this.memberof = '';
        this.employee = '';
        this.siccode = '';
        this.rating = '';
        this.ownership = '';
        this.vendorcode = '';
    }
}
export class AccountModelWithResponse extends ResponseBase {
    data: Array<AccountModel>;
    account: AccountModel;
    constructor() {
        super();
        this.data = Array<AccountModel>();
        this.account = new AccountModel();
    }
}